name: Build mongo_prune

on:
  push:
    paths:
      - prod/Prune.dockerfile
      - setup/mongo_prune_requirements.txt
  schedule:
    - cron: "0 0 * * 6"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./prod/Prune.dockerfile
          push: false
          platforms: linux/amd64
          tags: mongo_prune:latest

      - name: Run Docker image
        run: docker run --rm mongo_prune:latest
